### ISSUE TITLE
CONVERT INTO REACT 

### ISSUE THREAD

**Issue by Vijaykv5** [KendallDoesCoding/youtubers-birthdays#57]
I think it's better to convert the entire website to React JS

**Comment by KendallDoesCoding** [comment]
maybe something we can do in the future.

**Comment by IAmRiteshKoushik** [comment]
Hey @KendallDoesCoding , considering that the entire website is more along the lines of a static site, would it be a better idea to convert it in a smaller and more agile framework like Vue.js or Svelte.js rather than React ? React is usually good with big/complex projects and smaller projects are better managed with the above mentioned frameworks. Thoughts ?

**Comment by KendallDoesCoding** [comment]
We have converted the website to MongoDB little more than a month ago.
